apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafbat
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  sources:
    - repoURL: https://kafbat.github.io/helm-charts
      targetRevision: 1.5.0
      chart: kafbat-ui
      helm:
        releaseName: kafbat-ui
        valueFiles:
          - $values/kafbat/values/values-infra.yaml
    - repoURL: https://github.com/kyumin1227/gitops-test-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
